### ISSUE TITLE
Issues with connecting to server.

### ISSUE THREAD

**Issue by ril3y** [itzg/docker-minecraft-bedrock-server#1]
I keep getting this error from all clients when trying to connect to this server:
**you need to authenticate to microsoft servers**

I am not sure how to fix this?  Any Ideas?

**Comment by itzg** [comment]
I was having that issue until I used the "Sign In" button, shown here in the lower left:

![IMG_E81DC26A682F-1](https://user-images.githubusercontent.com/988985/61962852-1856bd80-af90-11e9-9b4d-4ff5c080fb33.jpeg)

**Comment by g3kk0** [comment]
For anyone else experiencing this and who doesn't wish to sign into Microsoft you can simply set `online-mode=false` in the `server.properties` file (within the docker volume) to get around it.

**Comment by DeGariless** [comment]
I too am having this issue. I have tried logging in with multiple accounts. I can login to other servers just fine. I tried running a local server off my windows machine and it worked and logged in just fine. I am having a really hard time narrowing down what the issue is caused be but it looks like its a problem with the server side.

**Comment by itzg** [comment]
@DeGariless one solution that weirdly worked in some cases was noted in https://github.com/itzg/docker-minecraft-bedrock-server/issues/29 was adding the tcp binding as `-p 19132:19132` along with the UDP one.

**Comment by shmilyoo** [comment]
If you do not change the online-mode, it is as default true.  And then even if you had login microsoft account, you still will probably have a error tip when connecting to the server, because the internect connection issue.
