### ISSUE TITLE
How can i forward port from docker?

### ISSUE THREAD

**Issue by rakeshb5615** [itzg/docker-minecraft-bedrock-server#124]
My friend who lives in another town, both of us want to play together on a Minecraft server, i created one but it is only accessible for me. i googled about playing with friends on a server and i got port forwarding a solution. i know tcp port forwarding using ngrok, but i don't know udp port forwarding. anyone help me.

**Comment by itzg** [comment]
I wasn't familiar with ngrok, but reading through the docs I also don't see support for UDP. 

The way I do it is with my router's port forwarding

https://www.asus.com/support/FAQ/114093/

and accessing the server my public IP address allocated by my internet provider.

**Comment by ske5074** [comment]
I skirted the whole multiple port issue and gained the benefit that local LAN hosts can autodetect my servers by using a macvlan interface.  This way each docker instance is seen as a separate server with it's own IP address using 19132udp.    This is partly due to my inability to get any proxy handling to work.  In case it's helpful:

Created a new network called macvlan_net.  I'm using a 255.255.0.0 subnet mask on my router so I can dedicate the entire 10.0.2.0/24 range to docker.  If you have a regular subnet mask of 255.255.255.0 you may need to change the subnet to 10.0.0.0/24 and select a range within that space that will not interfere with any DHCP stuff going on.  My DHCP is 10.0.0.10-200 so the 10.0.2.0/24 space keeps docker from clobbering anyone else on the network.

# docker network create -d macvlan -o parent=eth0 --subnet 10.0.0.0/16 --gateway 10.0.0.1 --ip-range 10.0.2.0/24 macvlan_net

docker-compose.yml below.  Notice you can tell docker the IP address explicitly of you prefer.  
version: '3.4'
services:
  family:
    hostname: family1
    image: itzg/minecraft-bedrock-server
    restart: unless-stopped
    environment:
      SERVER_NAME: "Family 1 - Survival"
      MAX_THREADS: 2
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: easy
      DEFAULT_PLAYER_PERMISSION_LEVEL: operator
    networks:
      default:
        #ipv4_address: 10.0.2.10
    ports:
      - 19132:19132/udp
    volumes:
      - ./family1:/data
    stdin_open: true
    tty: true

  family2:
    hostname: family2
    image: itzg/minecraft-bedrock-server
    restart: unless-stopped
    environment:
      SERVER_NAME: "Family 2 - New World"
      MAX_THREADS: 2
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: easy
      DEFAULT_PLAYER_PERMISSION_LEVEL: operator
      LEVEL_SEED: 424242
    networks:
      default:
    ports:
      - 19132:19132/udp
    volumes:
      - ./family1:/data
    stdin_open: true
    tty: true

networks:
   default:
      external:
        name: macvlan_net`
