### ISSUE TITLE
Unable to run commands inside container using kubernetes.

### ISSUE THREAD

**Issue by darkcloud784** [itzg/docker-minecraft-bedrock-server#132]
I run my container using Kubernetes. I exec into it as detailed in your documentation, it execs me in as root but I just get bash shell and I'm unable to run any server commands.

![image](https://user-images.githubusercontent.com/989990/106669232-f967bd00-6570-11eb-94d0-2172f6b9ac2f.png)

Also, the ability to apply something like gamerule showcoordinates true through env would be amazing.

**Comment by itzg** [comment]
You might be mixing up the Java edition instructions. Exec'ing into the bedrock container is not useful since there's no rcon or anything and you must have exec'ed `bash` which runs...bash. 

Instead the instructions say to `attach` to the container in order to run Minecraft bedrock commands against the bedrock process.

**Comment by darkcloud784** [comment]
> 
> 
> You might be mixing up the Java edition instructions. Exec'ing into the bedrock container is not useful since there's no rcon or anything and you must have exec'ed `bash` which runs...bash.
> 
> Instead the instructions say to `attach` to the container in order to run Minecraft bedrock commands against the bedrock process.

Thanks, I think I just misunderstood the details. I was able to attach to my pod and run commands I wanted to.
