### ISSUE TITLE
Monitoring logs for player connect / disconnect

### ISSUE THREAD

**Issue by TemporalAgent7** [itzg/docker-minecraft-bedrock-server#143]
Hi,

It looks like Bedrock Server is missing the required API for querying status. I noticed you have a mc-monitor integration with optional Prometheus support but that can only display things like number of online players.

The stdout from ./bedrock-server includes entries like these:
```
[INFO] Player connected: <tag>, xuid: <a_xuid>
[INFO] Player disconnected: <tag>, xuid: <a_xuid>
```

Before I go rolling a custom hack that monitors the container logs (or fork your awesome project) I was wondering if we'd want to do something in the base image for this. Something that can be webhooked (Prometheus or plain-old HTTP API) for when players connect or disconnect (with player tag) would be awesome.

Thank you!

**Comment by itzg** [comment]
Do you mean specifically the ability to query for currently connected player IDs?

Since the container startup script exec's the bedrock binary at the end, I'm not sure if log processing and serving an additional API process is something I'd want to include in the base image. 

I'd prefer Mojang add this in the first place; however, I suspect they're hesitant to expose a player list to unauthenticated queries since it would compromise player privacy on public servers. 

As you mentioned, forking is an option and might have to be the way in this case.

**Comment by TemporalAgent7** [comment]
I understand, thank you for your reply.
