### ISSUE TITLE
replace makefile?

### ISSUE THREAD

**Issue by AnalystCave** [itzg/docker-minecraft-bedrock-server#144]
Hi I restarted my server today to see this message
"Downloading Bedrock server version 1.16.221.01..."
now the server console is asking 
"replace Makefile? [y]es, [n]o, [A]ll, [N]one, [r]ename"

I want to keep my World progress without change - what do I need to type? y or n?

**Comment by itzg** [comment]
I haven't noticed before that the server archive includes a `Makefile`. In any case it's safe to say "y" to replace it.

**Comment by itzg** [comment]
...looking at its contents, I'm pretty sure they didn't mean to include that file with the archive. That file is for them to actually build the executable.

**Comment by itzg** [comment]
The latest image should now fix this.

**Comment by AnalystCave** [comment]
Thanks! I put 'y' and it ran all fine

**Comment by itzg** [comment]
Hmm, with the latest image it should have stopped prompting. Glad it's all working in the end in any case.

**Comment by awatney** [comment]
I also noticed the issue today when the container was showing unhealthy.  After a bunch of stop and starts because of multiple errors, I got things working.  The two weird things are that I had to yes to a couple more items then just the makefile (shown in the log file below)
![image](https://user-images.githubusercontent.com/19160951/116016757-3fc63880-a603-11eb-8dc2-36e5b9ddeb4f.png)

The other curious thing was the image name that is showing up with 56db*
![image](https://user-images.githubusercontent.com/19160951/116016927-c549e880-a603-11eb-98e2-af398c7fa380.png)


Does it make any sense on why, even with the newest image (I pull 'itzg/minecraft-bedrock-server:latest'), I'm getting the stop until I answer 'Y' to the three questions?  Great image though!

Adam

**Comment by itzg** [comment]
Strange, the `-n` in 

https://github.com/itzg/docker-minecraft-bedrock-server/blob/3cf8c20ca4cfb40afa0d439c935d8a0d267a055c/bedrock-entry.sh#L102

tells `unzip` to not overwrite files and therefore not prompt.

@awatney interesting point on the image references. Portainer seems to have latched onto a specific image SHA and is no longer referencing the image label itself. That would explain why the old behavior is still happening.

**Comment by itzg** [comment]
@awatney ah yes, I found that image ID in my history and it's a build from 6 weeks ago:

```
itzg/minecraft-bedrock-server   <none>    56db09780619   6 weeks ago    165MB
```

**Comment by awatney** [comment]
@itzg Thanks!  I duplicated the container and started this new one in Portainer and it did get the newest image and all is good.  Thanks again for all your work on keeping the image current...it is greatly appreciated.
