### ISSUE TITLE
LAN connection issues

### ISSUE THREAD

**Issue by ndaman** [itzg/docker-minecraft-bedrock-server#26]
I am running this docker container from a local home server, and for the most part it works wonderfully. My problem is connecting as a LAN game (which is necessary to play on the xbox). I can enter the IP address form my Windows 10 machine and connect just fine, but it does not show up on LAN. I thought it might be a firewall, but the issue persists even after disabling my firewall, any ideas how I can debug this? Thanks!

EDIT: Actually, I'm not sure I was actually able to disable the Firewall, as that messes with Docker (I'm using iptables). I did follow in a similar discussion and while docker ps and lsof both seem fine, the tcpdump command is empty

```
tcpdump -v udp port 19132
dropped privs to tcpdump
tcpdump: listening on docker_gwbridge, link-type EN10MB (Ethernet), capture size 262144 bytes
```

**Comment by itzg** [comment]
Glad to hear you found the other thread since I was going to suggest monitoring with tcpdump to see if the broadcast packets were arriving at your host.

I actually haven't paid a lot of attention to what docker is dong with my iptables each time, I just know it puts a lot of stuff there. I could have sworn at one point it adds an "accept" rule as a port mapping is declared on containers.

Since the tcpdump capture was empty, then I recommend investigating your network topology. Specifically, I'm pretty sure your xbox and linux host will both need to be on the same network segment, specifically both configured to route via the same gateway IP address.

FWIW, I have been pleasantly surprised to see my xbox auto discover my bedrock container running on Ubuntu, but my host and xbox are both on the same router/mesh network.

**Comment by ndaman** [comment]
Thanks for the help. In regards to network topology: everything is going through the same router and is on the same subnet. I was hoping the problem might be related to port forwarding (many others cited a need to forward both udp and tcp from their router), but doing that does not fix my issue.

I feel like something must be wrong with my tcpdump command or setup, if I am connected to the server (by manually entering the IP address), isn't that traffic going through port 19132?

**Comment by ndaman** [comment]
I'm not sure what exactly solved the problem, in part because some of my debugging efforts may have not discovered what I had intended, but I'm going to document what I did and mark this as closed.

1. One issue that persists: My XBox can see the local server now, which is all I needed. I was debugging using my Windows 10 PC, which could already connect by typing in the local IP address manually. My PC version of minecraft still does not show the server locally, even though the XBox does, I am wondering if this is because it already has the server saved remotely, and won't show the same server in two locations? Otherwise I'm not sure what's going on there.
2. I had initially assumed no port forwarding on my router would be needed since everything was on the same local subnet, but following some other suggestions from various sources, I opened 19132 to both tcp and udp on my router (I also added tcp forwarding of port 19132 to my docker start command)
3. My last resort was to try using [BedrockConnect](https://github.com/Pugmatt/BedrockConnect), but after I changed my dns servers per the instructions and logged into Minecraft on the XBox, I could see my local server, so the rest was not needed.

If I get the urge to see which of these actually solved the problem I might update this, but for now it behaves as I want it to and I'm happy with it. Thanks for your help!
