### ISSUE TITLE
Game Settings are disabled.

### ISSUE THREAD

**Issue by mbarela82** [itzg/docker-minecraft-bedrock-server#50]
I'm new to this. I'm not sure if this is something that happens with a server but I can't change game settings. Also, are achievements disabled on the Bedrock Server?

![Screenshot (2)](https://user-images.githubusercontent.com/9934970/80838205-b6c61e00-8bb5-11ea-90eb-660f41ffaf65.png)

**Comment by TheOriginalWebasdf** [comment]
I am having trouble also.  I added file ops.txt and admin.txt to the /data directory (with my Xbox username) and that didn't work.  

I also tried adding myself to the permissions.json file.  
/var/lib/docker/volumes/1d58659676167a387796f294c5b30f3c51ade1604484dbe1aa01236d9bcf199c
I even set the default-player-permission-level in server.properties to operator.  I'm still not operator.

**Comment by itzg** [comment]
- I'm [not finding any specific evidence](https://www.google.com/search?q=bedrock+dedicated+server+achievements), but observing how creative mode disables achievements I'm thinking Mojang/Microsoft don't want to taint Xbox user achievements due to a possibly hacked server
- Server settings can't be changed through the client. **On initial world creation** [settings can be configured via container env vars](https://github.com/itzg/docker-minecraft-bedrock-server#server-properties)
- Since Mojang's bedrock dedicated server software is still alpha it seems to have bugs about not consulting the properties file after the world has been generated. Instead you will need to `docker attach` to the server, [run the appropriate commands](https://minecraftbedrock.fandom.com/wiki/Commands/List_of_Commands), and detach using Ctrl-p Ctrl-q
- All permissions files in bedrock edition use the **XUID** which is a numerical ID and not the Xbox gamertag. Use [something like this](https://cxkes.me/xbox/xuid) to convert a gamertag to an xuid...however, if you use the `docker attach` approach above you can `op "Xbox Gamertag"` after the player has joined to convert and persist their permission.
