### ISSUE TITLE
Suppress "AutoCompaction" Logs?

### ISSUE THREAD

**Issue by xnaas** [itzg/docker-minecraft-bedrock-server#60]
Is it possible to suppress the `Running AutoCompaction...` log line so running something like `docker-compose logs -f minecraft` doesn't require 12 miles of scrolling to see anything other than `Running AutoCompaction...` message? :D

**Comment by itzg** [comment]
I don’t know if a way directly, but it’s definitely annoying. I would suggest opening an issue here


https://bugs.mojang.com/projects/BDS/issues/BDS-5638?filter=allopenissues

**Comment by xnaas** [comment]
I've submitted https://bugs.mojang.com/browse/BDS-5644

**Comment by xnaas** [comment]
Looks like they closed it as "invalid" and redirected to a "put a suggestion into Reddit or a web form" to forever be ignored. That's highly unfortunate. 🙃

**Comment by itzg** [comment]
Well that's a bummer they marked it invalid. Feel free to post the reddit link here and I'll upvote it.

**Comment by xnaas** [comment]
I never got around to posting anything, but it looks like this might be resolved now anyway? 🙃

**Comment by tgwaste** [comment]
Its most definitely not resolved and so.. damn.. annoying.

**Comment by adamnoffie** [comment]
5 years later, still annoying. :(

**Comment by itzg** [comment]
And still outside my control. Would be great for someone to attempt again reporting the issue with Mojang.

**Comment by adamnoffie** [comment]
Yeah, sorry didn't mean for you to feel slighted or maligned at all.
Understand it is part of the server software itself. Does someone have a
link to where you report feature requests to Mojang for dedicated server?

On Thu, Feb 20, 2025, 9:53 PM Geoff Bourne - notifications(a)github.com
<github+reply+AAAYCQTXC3D3W37EUFKJKD6FYPM3REVBNHHCKQ3AUI=

**Comment by itzg** [comment]
No problem at all @adamnoffie 😄 

This seems to be the best way to start in their issue tracker

https://bugs.mojang.com/projects/BDS/issues/BDS-5638?filter=allopenissues

**Comment by YouRexcellent** [comment]
I used to log the output of bedrock_server by piping it to "| tee output.log".  Not long ago, I switched to SCREEN so that I could have a command-line interface to bedrock_server.  I still logged the output using screen's "--Logfile" switch.  In both cases, I would see the "Running AutoCompaction" message every 6 minutes.  Very annoying!

Recently, I noticed that my system swap usage was growing out of control.  In an effort to troubleshoot that issue, I stopped logging the output of bedrock_server.  Guess what... Swap usage is reasonable and AutoCompaction is non-existent.

Does this have anything to do with the latest version: 1.21.61.01?
Does "AutoCompaction" have anything to do with logging standard output?
Do I understand what is happening?
Can someone explain what's happening?
Will this work for you?

The answer to all of these is "I don't know.", but I felt it worth commenting.

Cheers.

**Comment by MicroNateId** [comment]
Anyone ever figure this out?

**Comment by MicroNateId** [comment]
Nevermind, finally found it - need to update to the latest server.properties file:
https://www.reddit.com/r/Minecraft/comments/g418pa/autocompaction/

**Comment by itzg** [comment]
That post was misleading. **Compression** has nothing to do with **compaction**. There must be another property that helps lower compaction rate.
