### ISSUE TITLE
Changing Gamemode once a world has been created

### ISSUE THREAD

**Issue by adrianplambert** [itzg/docker-minecraft-bedrock-server#64]
Is this not possible? I've tried editing the docker-compose.yml file and using it to restart and also editing the server.properties file within the container. Still the gamemode doesn't change.

**Comment by itzg** [comment]
Unfortunately the bedrock server itself seems to ignore most of the server properties after the world has been generated. I'm guessing that's because they become dynamic properties of the world data itself. Instead, you will need to `docker attach` to the container, [issue commands such as `/gamemode`,](https://minecraftbedrock.fandom.com/wiki/Commands/List_of_Commands) and detach using Ctrl-p, Ctrl-q.

**Comment by adrianplambert** [comment]
Thanks. That worked. 

Also I noticed when I opped a player the changes this player made in game to the gamemode were also ignored. Ie the player goes to settings on an iOS device and changes the game mode from there. Upon returning to the game the game mode is unchanged. So it seems docker attach is the only way that works for this.
