### ISSUE TITLE
feature request - console logging

### ISSUE THREAD

**Issue by MattrCoUk** [itzg/docker-minecraft-bedrock-server#82]
Would it be possible to add the server’s console logging functinality? Ideally to a file(s) located in the mounted volume.
I don’t think Bedrock has this functionality but I am assuming it could be accomplished with a little sh script inside the container. (Sorry if I’m talking rubbish, not really a dev.)
I could possibly help if someone points me in  the right direction :-)

**Comment by itzg** [comment]
That's a fair request; however, it goes against the logging abstraction provided by Docker

https://docs.docker.com/config/containers/logging/configure/

It's actually a feature of Docker that container processes simply "log" to console and then let the Docker daemon manage the storage/forwarding of those logs.

Besides, file based logging is actually a little hard to properly solve since you have to think about log file limits, rolling over files, pruning older log files, etc.

Just to make sure I'm not missing something, what would you find beneficial about a log file vs using `docker logs`?

**Comment by MattrCoUk** [comment]
> Besides, file based logging is actually a little hard to properly solve since you have to think about log file limits, rolling over files, pruning older log files, etc.

Yeah, that’s true. Was hoping there are some out of the box solutions. Will have a a look into the docker logging system, perhaps it is enough. Thanks

**Comment by MattrCoUk** [comment]
Turns out that a simple `docker info <container name>` seems to do the job :-)
